### ISSUE TITLE
nx.text() errors

### ISSUE THREAD

**Issue by jacob-roth** [kwgoodman/numerox#14]
I'm just becoming familiar with `numerox` and `pip` installed for python 3 :
```
Successfully installed numerapi-1.0.1 numerox-1.4.0 tqdm-4.23.3
```
and tried running `nx.test()` but received 2 errors:
```
Running unit tests for numerox
NumPy version 1.14.0
NumPy relaxed strides checking option: True
NumPy is installed in /Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/numpy
Python version 3.5.3 |Anaconda 4.4.0 (x86_64)| (default, Mar  6 2017, 12:15:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
nose version 1.3.7
....................................E..............E............
======================================================================
ERROR: prediction.drop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/numerox/tests/test_prediction.py", line 138, in test_prediction_drop
    p = p.drop(['model1'])
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/numerox/prediction.py", line 66, in drop
    df = self.df.drop(columns=name)
TypeError: drop() got an unexpected keyword argument 'columns'

======================================================================
ERROR: make sure prediction.__repr__() runs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/numerox/tests/test_prediction.py", line 316, in test_prediction_repr
    p.__repr__()
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/numerox/prediction.py", line 497, in __repr__
    frac_miss = self.df.isna().mean().mean()
  File "/Users/MYUSER/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'isna'

----------------------------------------------------------------------
Ran 64 tests in 10.051s

FAILED (errors=2)
```

Just wanted to highlight for attention, and I'll look into as well as I become more familiar with the repo.

**Comment by kwgoodman** [comment]
That is weird. What version of pandas are you using:
```
In [1]: import pandas as pd
In [2]: pd.__version__
Out[2]: u'0.23.0'
```
What is the function signature of DataFrame.drop on your version? Using ipython:
```
df = pd.DataFrame()
df.drop?
```
gives
```
Signature: df.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
```
